name: Deploy Student Interface

on:
  push:
    branches:
      - main
    paths:
      - 'code/Student_interface/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/Student_interface
    steps:
      - uses: actions/checkout@v4
      - run: npm install --legacy-peer-deps && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VPS_2K25_APP }}
          channelId: live
          projectId: vps-2k25-app
          target: student
